name = "hugo-dsfr"
license = "MIT"
licenselink = "https://github.com/filo31410/testhugo/blob/main/LICENSE"
description = "Theme simple integrant des composants du DSFR"
homepage = "https://github.com/filo31410/testhugo/"
demosite = "https://filo31410.github.io/testhugo.github.io/"
tags = ["hugo", "dsfr"]
features = ["actualites"]
min_version = "0.20"

[author]
  name = "Laurent Déprez"
  homepage = "https://github.com/filo31410"
